
# WARNING this is a developer makefile, not generated by Autotools.

check:
	( cd `uname` && $(MAKE) check )

install:
	if [ -d `uname` ]; then ( cd `uname` && $(MAKE) install ) ; fi
	if [ -d `uname`64 ]; then ( cd `uname`64 && $(MAKE) install ) ; fi

clean:
	( cd src && $(MAKE) clean )
	( cd `uname` && $(MAKE) clean )

bu:
	echo `find . -name '*~'`
	rm -f `find . -name '*~'`
