#!MC 1410
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!PAGE NAME = 'Untitled'
$!PAGECONTROL CREATE
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!OPENLAYOUT  "accept-3d.lay"
$!PRINTSETUP PALETTE = COLOR
$!EXPORTSETUP USESUPERSAMPLEANTIALIASING = YES
$!EXPORTSETUP CONVERTTO256COLORS = YES
$!EXPORTSETUP EXPORTFNAME = 'accept-3d.png'
$!EXPORT 
  EXPORTREGION = CURRENTFRAME
