
QUIET = @$(MAKE) --quiet --no-print-directory

test:
	./adjMT.rb
	./nearMT.rb
	./lineMT.rb
	./intersectMT.rb
	./gridMT.rb
	./gridcadMT.rb
	./gridmathMT.rb
	./gridmetricMT.rb
	./gridswapMT.rb
	./gridinsertMT.rb
	./layerMT.rb
	./sampleunitMT.rb

clean:
	rm -rf Adj Grid* Intersect Layer Line Near SampleUnit grid.t
